# Endpoint to access DynamoDB
dynamo-endpoint: dynamodb.us-east-1.amazonaws.com

# Approved Application Authentication Credentials
approved-keys:
  - application: application
    secret: secret

# Server configuration
server:
    applicationConnectors:
        - type: http
          port: 8080
    adminConnectors:
        - type: http
          port: 8081