name: Generate Release Notes

on:
  milestone:
    types: [closed]

jobs:
  create-release-notes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Create release notes
        uses: Decathlon/release-notes-generator-action@v2.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload release notes
        uses: actions/upload-artifact@v2
        with:
          name: release-notes
          path: release_file.md

  merge-release-notes:
    runs-on: ubuntu-latest
    needs: [create-release-notes]

    steps:
      - uses: actions/checkout@v2
      - name: Download release notes
        uses: actions/download-artifact@v2
        with:
          name: release-notes
      - name: Merge into CHANGELOG
        run: |
          sed -i "1s/^/# $MILESTONE_TITLE\n/" release_file.md # Add the milestone title
          echo "" >> release_file.md # Add two new lines
          echo "" >> release_file.md
          cat release_file.md # Show contents for debugging
          mkdir out/
          cat release_file.md CHANGELOG.md > out/CHANGELOG.md # Merge release notes and existing changelog
          cat out/CHANGELOG.md > CHANGEGLOG.md
          rm release_file.md
        env:
          MILESTONE_TITLE: ${{ github.event.milestone.title }}
      - name: Create pull request
        uses: peter-evans/create-pull-request@v2
        with:
          branch: github-actions/changelog
          title: Update CHANGELOG.md
          body: Update CHANGELOG.md
          commit-message: Update CHANGELOG.md
          labels: "Type: Releases,Size: Small"
